data=["IBM",98.6,45,[13,9,2024]]
# name,share,price,date=data
# print(name,share,date,price)
d={"one":1,"two":2}
# for i in d.items():
#     a,b=i
#     print(a+" ",b)
# for i in enumerate(data):
#     a,b=i
#     if type(b)==list:
#         j,k,l=b
#         print(a,j,k,l)
#     else:
#      print(a,b)   
#for i in d.items():
    #print(i)
#print(i for i in d.items())
#print(d)
# a=[1,2,3]
# b=[4,5,6]
# for item in zip(a,b):
#print(item)

